apps/psychologist/urls.py
from django.urls import path, include

from .views import (
    HomePage, 
    PsychologistListView, 
    PsychologistDetailView, 
    PsychologistCreateView
)


urlpatterns = [
    path('', HomePage.as_view(), name='homepage'),
    path('psychologits/', PsychologistListView.as_view(), name='list_psycholog'),
    path('psychologits/<str:slug>', PsychologistDetailView.as_view(), name='psychologist_detail'),
    path('create-psychologist/', PsychologistCreateView.as_view(), name='__create'),
]

clearly/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.psychologist.urls')),
    path('blogs/', include('apps.blogs.urls')),
    path('', include('apps.makeIN.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/psychologist/models.py
from django.db import models
from django.urls import reverse


class AdditionalSpecialization(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Дополнительная специалиция"


class MainSpecialization(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Основная Специализации"


class PsychologistStatus(models.Model):
    """Модель статуса психолога"""
    title = models.CharField(max_length=40)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Статус Психологи"


class Psychologist(models.Model):
    """Модель Психолога"""
    active = models.BooleanField(null=True, blank=True)
    image = models.FileField(
        upload_to='psychologist', 
        null=True, 
        blank=True
    )
    
    SEX_CHOICES = [
        ("Мужской", "Мужской" ),
        ("Женский", "Женский" ),
    ]
    online_consultation_CHOICES = [
        ('Да', 'Да'),
        ('Нет', 'Нет'),
    ]
    surname = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    sex = models.CharField(max_length=7, choices=SEX_CHOICES)
    brief_description_work = models.CharField(max_length=500)
    bio = models.TextField(null=True, blank=True)
    education = models.TextField(null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)

    status = models.CharField(max_length=200)
    main_specialization = models.CharField(max_length=200)
    
    additional_specialization_one = models.CharField(max_length=200)
    # additional_specialization_two = models.ForeignKey(AdditionalSpecialization, on_delete=models.SET_DEFAULT, default='None', null=True, blank=True)
    # additional_specialization_three = models.ForeignKey(AdditionalSpecialization, on_delete=models.SET_DEFAULT, default='None', null=True, blank=True)

    online_consultation = models.CharField(max_length=3, choices=online_consultation_CHOICES)
    cost_of_online_consultation = models.IntegerField(help_text='руб', null=True, blank=True)

    personal_reception = models.CharField(max_length=3, choices=online_consultation_CHOICES) 
    cost_of_personal_reception = models.IntegerField(help_text='руб', null=True, blank=True)

    address_of_the_reception_room = models.CharField(max_length=500, null=True, blank=True)

    phone = models.CharField(max_length=20)
    # social
    skype = models.CharField(max_length=100, null=True, blank=True)
    instagram = models.CharField(max_length=100, null=True, blank=True)
    facebook = models.CharField(max_length=100, null=True, blank=True)
    twitter = models.CharField(max_length=100, null=True, blank=True)

    slug = models.SlugField(unique=True, blank=True, null=True)

    def __str__(self):
        return f"{self.surname}-{self.name}"
    

    def get_absolute_url(self):
        return reverse("psychologist_detail", kwargs={"slug": self.slug})


    class Meta:
        verbose_name_plural = "Психологи"

apps/psychologist/forms.py
from django import forms

from apps.psychologist.models import Psychologist


class PsychologistForm(forms.ModelForm):
    image = forms.ImageField()
    
    class Meta:
        model = Psychologist
        # fields = (
        #     'image', 
        #     'surname', 
        #     'name', 
        #     'country', 
        #     'sex', 
        #     'brief_description_work',
        #     'bio', 
        #     'education', 
        #     'email', 
        #     'status', 
        #     'main_specialization', 
        #     'additional_specialization_one',
        #     'online_consultation',
        #     'cost_of_online_consultation',
        #     'personal_reception',
        #     'cost_of_personal_reception',
        #     'phone',
        #     'skype',
        #     'instagram',
        #     'facebook',
        #     'twitter',
        # )

        fields = "__all__"
        exclude = ('active', 'slug',)

apps/psychologist/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic.base import View
from django.views.generic import DetailView, ListView, CreateView

from django.urls import reverse_lazy

from apps.psychologist.models import Psychologist
from apps.psychologist.forms import PsychologistForm
from apps.homepage.models import SettingsHomePage

class PsychologistListView(ListView):
    model = Psychologist
    queryset = model.objects.filter(active=True)
    template_name = "psychologist/list_psychologist.html"
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['setting'] = SettingsHomePage.objects.get(id=1)
        return context

class PsychologistDetailView(DetailView):
    model = Psychologist
    slug_field = 'slug'
    template_name = 'psychologist/psycholog-detail.html'

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['setting'] = SettingsHomePage.objects.get(id=1)
        return context


class HomePage(View):
    def get(self, request):
        psychologists = Psychologist.objects.filter(active=True)
        setting = SettingsHomePage.objects.get(id=1)
        return render(request, 'homepage/index.html', locals())


class PsychologistCreateView(CreateView):
    model = Psychologist
    form_class = PsychologistForm
    template_name = "forms/add-form-psy.html"
    success_url = reverse_lazy('finish_form')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['setting'] = SettingsHomePage.objects.get(id=1)
        return context

templates/psychologist/list_psychologist.html
{% extends "base/base.html" %}
{% load static %}

{% block psycholog %}active{% endblock psycholog %}

{% block content %}

	<section class="ls section_padding_top_130 section_padding_bottom_100 columns_margin_top_0 columns_margin_bottom_30">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 text-center">
					<h2 class="section_header with_icon">Психологии</h2>
					<p>
						Я хочу разминаться с короткими ребрышками коровы в солонине, как Кевин. Футбольные сосиски с ветчиной рулькой винят в откорме сама по себе вяленая вырезка какая-то.
					</p>
				</div>
			</div>
			<div class="row">
				{% for pl in psychologist_list %}
				<div class="col-md-4 text-center">
					<article class="vertical-item content-padding post format-standard with_shadow">

						<div class="item-media entry-thumbnail">
							<img src="{{ pl.image.url }}" alt="">
						</div>

						<div class="item-content entry-content">
							<header class="entry-header">

								<div class="entry-date small-text highlight">
									<a href="blog-right.html" rel="bookmark">
										<time class="entry-date" datetime="2017-03-13T08:50:40+00:00">
											{{ pl.main_specialization }}
										</time>
									</a>
								</div>

								<h4 class="entry-title">
									<a href="{{ pl.get_absolute_url }}" rel="bookmark">{{ pl.name }} {{ pl.surname }}</a>
								</h4>

								<hr class="divider_30_1">

							</header>
							<!-- .entry-header -->

							<p class="bottommargin_40 fontsize_18">{{ pl.bio|truncatewords:11 }}</p>

							<a href="{{ pl.get_absolute_url }}" class="theme_button color1">Смотреть польностью</a>

						</div>
						<!-- .item-content.entry-content -->
					</article>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>

{% endblock content %}

templates/psychologist/psycholog-detail.html
{% extends "base/base.html" %}
{% load static %}

{% block psycholog %}active{% endblock psycholog %}

{% block content %}

	<section class="page_breadcrumbs ds background_cover section_padding_50">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 text-center">
					<h2>{{ psychologist.surname }}  {{ psychologist.name }}</h2>
					<h4>Psychologist</h4>
				</div>
			</div>
		</div>
	</section>

	<section class="ls section_padding_top_130 section_padding_bottom_130 columns_padding_25">
		<div class="container">
			<div class="row">

				<div class="col-sm-7 col-md-8 col-lg-8">

					<div class="vertical-item content-padding with_shadow">
						<div class="entry-thumbnail item-media">
							<img src="{{ psychologist.image.url }}" alt="">
						</div>

						<div class="item-content">


							<header class="entry-header">

								<!-- .entry-meta -->

								<div class="entry-date small-text highlight">
									<a href="" rel="bookmark">
										<time class="entry-date" datetime="2017-03-13T08:50:40+00:00">
											{{ psychologist.country }}
										</time>
									</a>
								</div>

								<h1 class="entry-title">
									{{ psychologist.surname }}  {{ psychologist.name }}
								</h1>
								<h1 style="font-size: 15px;">{{ psychologist.status }}</h1>

								<hr class="divider_30_1">

							</header>
							<!-- .entry-header -->

							<div class="entry-content">
								<p>
									{{ psychologist.bio }}
								</p>
							</div>
							<!-- .entry-content -->
							<hr class="divider_30_1">

							<div class="entry-content">
								<p>
									{{ psychologist.education }}
								</p>
							</div>
							<!-- .entry-content -->

							<hr class="divider_30_1">

							<div class="entry-content">
								<p>
									Основная специализация: {{ psychologist.main_specialization }}
								</p>
							</div>
							<!-- .entry-content -->
							<div class="entry-content">
								<p>
									Дополнительная специализация: {{ psychologist.additional_specialization_one }}
								</p>
							</div>
							<!-- .entry-content -->
							<hr class="divider_30_1">

							<div class="entry-content">
								<p>
									Цена за онлайн консультацию: {{ psychologist.cost_of_online_consultation }}₽
								</p>
							</div>
							<div class="entry-content">
								<p>
									Цена за личного приема: {{ psychologist.cost_of_personal_reception }}₽
								</p>
							</div>
							<hr class="divider_30_1">

							{% if psychologist.address_of_the_reception_room is not None %}
							<div class="entry-content">
								<p>
									Адрес приема: {{ psychologist.address_of_the_reception_room }}
								</p>
							</div>
							{% else %}
							{% endif %}



							{% if psychologist.blog_author is not None %}
							<div class="author-meta side-item content-padding">

								<h2 style="margin-bottom: -30px;">Все блоги</h2>
								{% for p in psychologist.blog_author.all %}
								<div class="row display_table_md">
									
									<div class="col-md-4 display_table_cell_md">
										<div class="item-media">
											<img src="{{ p.image.url }}" alt="">
										</div>
									</div>

									
									<div class="col-md-8 display_table_cell_md">
										<div class="item-content">
											<h4>{{ p.title }}</h4>

											<hr class="divider_30_1">

											<p>{{ p.description|truncatewords:10 }}</p>
											<!-- <div class="author-social"> -->
											<div class="author-social divided_content lightgreylinks">
												<span>
													<a class="social-icon soc-facebook" href="https://facebook.com/" target="_blank" title="Facebook" ></a>
												</span>
												<span>
													<a class="social-icon soc-twitter" href="https://twitter.com/" target="_blank" title="Twitter"></a>
												</span>
												<span>
													<a class="social-icon soc-google" href="https://google.com/" target="_blank" title="Google"></a>
												</span>
												<span>
													<a class="social-icon soc-linkedin" href="https://linkedin.com/" target="_blank" title="LinkedIn"></a>
												</span>
											</div>

										</div>
									</div>
									
								</div>
								{% endfor %}
							</div>
							{% else %}
							<div class="author-meta side-item content-padding">

								<h2 style="margin-bottom: -30px;">Нету Блогов</h2>
							</div>
							{% endif %}
						</div>

					</div>
				</div>
				<!--eof .col-sm-8 (main content)-->


				<!-- sidebar -->
				<aside class="col-sm-5 col-md-4 col-lg-4">


					<div class="widget widget_apsc_widget">
						<h3 class="widget-title">Связаться</h3>
						<div class="apsc-icons-wrapper clearfix apsc-theme-4">
							{% if psychologist.facebook %}
							<div class="apsc-each-profile">
								<a class="apsc-facebook-icon clearfix" href="{{ psychologist.facebook }}" target="_blank">
									<div class="apsc-inner-block">
										<span class="social-icon">
											<i class="fa fa-facebook apsc-facebook"></i>
											<span class="media-name">Facebook</span>
										</span>
									</div>
								</a>
							</div>
							{% else %}
							{% endif %}
							{% if psychologist.twitter %}
							<div class="apsc-each-profile">
								<a class="apsc-twitter-icon clearfix" href="{{ psychologist.twitter }}" target="_blank">
									<div class="apsc-inner-block">
										<span class="social-icon">
											<i class="fa fa-twitter apsc-twitter"></i>
											<span class="media-name">Twitter</span>
										</span>
									</div>
								</a>
							</div>
							{% else %}
							{% endif %}
							{% if psychologist.skype %}
							<div class="apsc-each-profile">
								<a class="apsc-google-plus-icon clearfix" href="{{ psychologist.skype }}" target="_blank">
									<div class="apsc-inner-block">
										<span class="social-icon">
											<i class="apsc-googlePlus fa fa-google-plus"></i>
											<span class="media-name">Skype</span>
										</span>
									</div>
								</a>
							</div>
							{% else %}
							{% endif %}
							{% if psychologist.instagram %}
							<div class="apsc-each-profile">
								<a class="apsc-instagram-icon clearfix" href="{{ psychologist.instagram }}" target="_blank">
									<div class="apsc-inner-block">
										<span class="social-icon">
											<i class="apsc-instagram fa fa-instagram"></i>
											<span class="media-name">Instagram</span>
										</span>
									</div>
								</a>
							</div>
							{% else %}
							{% endif %}
						</div>

					</div>


				</aside>
				<!-- eof aside sidebar -->

			</div>
		</div>
	</section>

{% endblock content %}